#!/usr/bin/env bash
# Run this script from the root directory of your project.
# Usage: source config/set_dev_env

ROOT_DIR=$(pwd)
SRC_DIR="$ROOT_DIR/src"

# Export PYTHONPATH variable to reflect root and src directories
export PYTHONPATH="$ROOT_DIR:$SRC_DIR"

# Load environment variables from .env
set -a  # Automatically export all variables
source "$ROOT_DIR/.env"
set +a  # Stop exporting all variables
